"""trainer_flow

Revision ID: 0858caf65a0d
Revises: 50092fe49f29
Create Date: 2026-05-26 19:15:04.803452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0858caf65a0d"
down_revision: Union[str, Sequence[str], None] = "50092fe49f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "COMPLETE", "INCOMPLETE", name="pokemonstatusenum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("pokeballs", sa.Integer(), nullable=False),
        sa.Column("capture_rate", sa.Integer(), nullable=False),
        sa.Column("base_capture_rate", sa.Integer(), nullable=False),
        sa.Column("capture_progress_points", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "owned_pokemons",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Integer(), nullable=False),
        sa.Column("defense", sa.Integer(), nullable=False),
        sa.Column("special_attack", sa.Integer(), nullable=False),
        sa.Column("special_defense", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("pokemon_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokedex",
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainer_encounters",
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("pokemon_encounter_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokemon_encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "owned_pokemon_moves",
        sa.Column("owned_pokemon_id", sa.Uuid(), nullable=False),
        sa.Column("pokemon_move_id", sa.Uuid(), nullable=False),
        sa.Column("pp", sa.Integer(), nullable=False),
        sa.Column("max_pp", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owned_pokemon_id"],
            ["owned_pokemons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_move_id"],
            ["moves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokedex_entries",
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Integer(), nullable=False),
        sa.Column("defense", sa.Integer(), nullable=False),
        sa.Column("special_attack", sa.Integer(), nullable=False),
        sa.Column("special_defense", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("pokedex_id", sa.Uuid(), nullable=False),
        sa.Column("pokemon_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("discovered", sa.Boolean(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokedex_id"],
            ["pokedex.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainer_parties",
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("owned_pokemon_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owned_pokemon_id"],
            ["owned_pokemons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trainer_parties")
    op.drop_table("pokedex_entries")
    op.drop_table("owned_pokemon_moves")
    op.drop_table("trainer_encounters")
    op.drop_table("pokedex")
    op.drop_table("owned_pokemons")
    op.drop_table("trainers")
    # ### end Alembic commands ###
