"""pokemon_catalog

Revision ID: 50092fe49f29
Revises: 527b69285dd7
Create Date: 2026-05-26 19:07:07.679076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '50092fe49f29'
down_revision: Union[str, Sequence[str], None] = '527b69285dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
                DO $$ BEGIN
                    CREATE TYPE pokemonstatusenum AS ENUM ('COMPLETE', 'INCOMPLETE');
                EXCEPTION
                    WHEN duplicate_object THEN null;
                END $$;
            """)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('flavor_text', sa.Text(), nullable=False),
    sa.Column('short_effect', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('chance', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('max_chance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('growth_rates',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('habitats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('back_image', sa.String(), nullable=False),
    sa.Column('front_image', sa.String(), nullable=False),
    sa.Column('back_source', sa.String(), nullable=False),
    sa.Column('front_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('moves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pp', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('flavor_text', sa.Text(), nullable=False),
    sa.Column('short_effect', sa.Text(), nullable=False),
    sa.Column('damage_class', sa.String(), nullable=False),
    sa.Column('effect_chance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('shapes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('badge_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('badge_icon_url', sa.String(), nullable=False),
    sa.Column('badge_shield_url', sa.String(), nullable=False),
    sa.Column('badge_legends_url', sa.String(), nullable=False),
    sa.Column('badge_legend_icon_url', sa.String(), nullable=False),
    sa.Column('badge_shield_icon_url', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='pokemonstatusenum', create_type=False), nullable=False),
    sa.Column('text_color', sa.String(), nullable=False),
    sa.Column('background_color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )

    op.create_table('pokemons',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('external_image', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETE', 'INCOMPLETE', name='pokemonstatusenum', create_type=False), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('special_attack', sa.Integer(), nullable=True),
    sa.Column('special_defense', sa.Integer(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('is_baby', sa.Boolean(), nullable=True),
    sa.Column('is_mythical', sa.Boolean(), nullable=True),
    sa.Column('is_legendary', sa.Boolean(), nullable=True),
    sa.Column('gender_rate', sa.Integer(), nullable=True),
    sa.Column('hatch_counter', sa.Integer(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('evolution_chain', sa.String(), nullable=True),
    sa.Column('evolves_from_species', sa.String(), nullable=True),
    sa.Column('has_gender_differences', sa.Boolean(), nullable=True),
    sa.Column('growth_rate_id', sa.Uuid(), nullable=True),
    sa.Column('habitat_id', sa.Uuid(), nullable=True),
    sa.Column('shape_id', sa.Uuid(), nullable=True),
    sa.Column('images_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['growth_rate_id'], ['growth_rates.id'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ),
    sa.ForeignKeyConstraint(['images_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['shapes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order')
    )

    op.create_table('type_strength_link',
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('type_strength_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_strength_id'], ['types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'type_strength_id')
    )
    op.create_table('type_weakness_link',
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('type_weakness_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_weakness_id'], ['types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'type_weakness_id')
    )

    op.create_table('pokemon_ability_link',
    sa.Column('pokemon_id', sa.Uuid(), nullable=False),
    sa.Column('ability_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id')
    )
    op.create_table('pokemon_encounter_link',
    sa.Column('pokemon_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pokemon_id', 'encounter_id')
    )
    op.create_table('pokemon_evolution_link',
    sa.Column('pokemon_id', sa.Uuid(), nullable=False),
    sa.Column('evolution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evolution_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pokemon_id', 'evolution_id')
    )
    op.create_table('pokemon_move_link',
    sa.Column('pokemon_id', sa.Uuid(), nullable=False),
    sa.Column('move_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id')
    )
    op.create_table('pokemon_type_link',
    sa.Column('pokemon_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_type_link')
    op.drop_table('pokemon_move_link')
    op.drop_table('pokemon_evolution_link')
    op.drop_table('pokemon_encounter_link')
    op.drop_table('pokemon_ability_link')
    op.drop_table('type_weakness_link')
    op.drop_table('type_strength_link')
    op.drop_table('pokemons')
    op.drop_table('types')
    op.drop_table('shapes')
    op.drop_table('moves')
    op.drop_table('images')
    op.drop_table('habitats')
    op.drop_table('growth_rates')
    op.drop_table('encounters')
    op.drop_table('abilities')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS pokemonstatusenum")
