"""trainer_log_flow

Revision ID: b88c467fcfd6
Revises: 0858caf65a0d
Create Date: 2026-05-29 16:08:07.867093

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b88c467fcfd6"
down_revision: Union[str, Sequence[str], None] = "0858caf65a0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
                        DO $$ BEGIN
                            CREATE TYPE logtypeenum AS ENUM ('PARTY', 'BATTLE', 'POKEDEX', 'TRAINER', 'POKEMON', 'ENCOUNTER');
                        EXCEPTION
                            WHEN duplicate_object THEN null;
                        END $$;
                    """)
    op.execute("""
                    DO $$ BEGIN
                        CREATE TYPE logstatusenum AS ENUM ('INFO', 'ERROR', 'SUCCESS', 'WARNING');
                    EXCEPTION
                        WHEN duplicate_object THEN null;
                    END $$;
                """)
    op.execute("""
                        DO $$ BEGIN
                            CREATE TYPE trainerlogeventenum AS ENUM ('WON', 'LOST', 'FLEE', 'SHOWN', 'MOVED', 'CREATED', 'UPDATED', 'DELETED', 'EXPLORED', 'CAPTURED', 'DISCOVERED');
                        EXCEPTION
                            WHEN duplicate_object THEN null;
                        END $$;
                    """)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trainer_logs",
        sa.Column("trainer_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "SHOWN",
                "PARTY",
                "BATTLE",
                "POKEDEX",
                "TRAINER",
                "POKEMON",
                "ENCOUNTER",
                name="logtypeenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "INFO",
                "ERROR",
                "SUCCESS",
                "WARNING",
                name="logstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "event",
            postgresql.ENUM(
                "WON",
                "LOST",
                "FLEE",
                "SHOWN",
                "MOVED",
                "CREATED",
                "UPDATED",
                "DELETED",
                "EXPLORED",
                "CAPTURED",
                "DISCOVERED",
                name="trainerlogeventenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trainer_logs_trainer_created",
        "trainer_logs",
        ["trainer_id", "created_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trainer_logs")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS logtypeenum")
    op.execute("DROP TYPE IF EXISTS logstatusenum")
    op.execute("DROP TYPE IF EXISTS trainerlogeventenum")
